= CloudBees action: Scan with SonarQube

If you already are running a centralized SonarQube instance, use this action to scan a Git repository with the SonarQube static analysis scanner. 
The data collected from the scans is available in your SonarQube reports, and the results are also displayed in the CloudBees platform analytics dashboards.

NOTE: If you do not have SonarQube already installed, use the https://github.com/cloudbees-io/sonarqube-bundled-sast-scan-code[Scan with SonarQube bundled action] instead.

== Inputs

[cols="2a,1a,4a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `url`
| String
| Yes
| The SonarQube server URL.

| `cmakeList-path`
| String
| No
| The `CMakeFileList.txt` file path for scanning C-family code languages.
For more information, refer to the link:https://cmake.org/cmake/help/book/mastering-cmake/chapter/Getting%20Started.html[CMake documentation].

| `password`
| String
| No
| The SonarQube password.

| `ref`
| String
| No
| The branch name to be scanned.

| `token`
| String
| No
| The SonarQube access token.

| `username`
| String
| No
| The SonarQube username.

| `workspace-dir`
| String
| No
| The file path of the code to be scanned.

|===

== Usage examples

The following is a basic example for using the action:

[source,yaml]
----

      - name: Scan with SonarQube
        uses: cloudbees-io/sonarqube-plugin@v1
        with:
          server-url: https://my-sonarqube-server-url

----

In the following example, the `cmakeList-path` input is specified for a C-family code language scan:

[source,yaml]
----

      - name: Scan C-family code with SonarQube
        uses: cloudbees-io/sonarqube-plugin@v1
        with:
          server-url: ${{ vars.SONARQUBE_SERVER_URL }}
          cmakeList-path: https://path/to/my/CMakeFileList.txt
----

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/actions[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].
